apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vaultUrl | quote }}
      tenantId: {{ .Values.tenantId | quote }}
