{{- if .Values.acrLoginServer }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-image-updater-credentials
  {{- include "estabilis.metadata" . | nindent 2 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: acr-image-updater-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .Values.acrLoginServer }}":{"username":"{{ .Values.acrTokenUsername }}","password":"{{ "{{ .acrToken }}" }}"}}}'
  data:
    - secretKey: acrToken
      remoteRef:
        key: {{ .Values.kvSecretName }}
{{- end }}
