{{- if .Values.policies.require_run_as_nonroot.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-nonroot
  labels:
    {{- include "estabilis.labels" . | nindent 4 }}
  annotations:
    {{- include "estabilis.annotations" . | nindent 4 }}
    policies.kyverno.io/title: Require Run As Non-Root
    policies.kyverno.io/description: >-
      Requires containers to run as a non-root user. Running as root inside a
      container increases the risk of container breakout and host compromise.
spec:
  validationFailureAction: {{ .Values.policies.require_run_as_nonroot.action | default "Audit" }}
  background: true
  rules:
    - name: run-as-nonroot-pods
      match:
        any:
          - resources:
              kinds:
                - Pod
{{ include "kyverno-policies.platform-exclude" . }}
      validate:
        message: "Containers must set runAsNonRoot to true."
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
    - name: run-as-nonroot-controllers
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
{{ include "kyverno-policies.platform-exclude" . }}
      validate:
        message: "Containers must set runAsNonRoot to true."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - securityContext:
                      runAsNonRoot: true
    - name: run-as-nonroot-cronjob
      match:
        any:
          - resources:
              kinds:
                - CronJob
{{ include "kyverno-policies.platform-exclude" . }}
      validate:
        message: "Containers must set runAsNonRoot to true."
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - securityContext:
                          runAsNonRoot: true
{{- end }}
